dist: trusty
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.6
  - 2.7
  #- 3.0

gemfile:
  - spec/gemfiles/rails-5.2.gemfile
  - spec/gemfiles/rails-6.0.gemfile
  - spec/gemfiles/rails-6.1.gemfile

# Rails 5.2 doesn't support Ruby 3.0, so don't try
matrix:
  exclude:
    - rvm: 3.0
      gemfile: spec/gemfiles/rails-5.2.gemfile

before_install: gem update bundler
bundler_args: --jobs 3
install: bundle install --jobs 3

script:
  - bash -c "if [ '$TRAVIS_RUBY_VERSION' = '2.7' ] && [[ '$BUNDLE_GEMFILE' == *'rails-6.1'* ]]; then bundle exec rubocop --fail-level autocorrect; fi"
  - bundle exec rspec
